# Generated by Django 6.0.8 on 2026-08-05 20:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alloy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('density', models.FloatField()),
                ('melting_point_min', models.IntegerField()),
                ('melting_point_max', models.IntegerField()),
                ('typical_applications', models.TextField(blank=True)),
                ('recommended_furnace', models.CharField(default='Induction Furnace', max_length=100)),
                ('estimated_holding_time', models.IntegerField(default=40)),
                ('mechanical_properties', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'alloys',
            },
        ),
        migrations.CreateModel(
            name='AlloyRawMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('purpose', models.CharField(max_length=200)),
                ('purity', models.FloatField()),
                ('estimated_recovery', models.FloatField()),
                ('supplier', models.CharField(max_length=100)),
                ('unit_cost', models.FloatField()),
            ],
            options={
                'db_table': 'alloy_raw_materials',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(db_index=True, max_length=100, unique=True)),
                ('current_stock', models.FloatField()),
                ('minimum_stock', models.FloatField()),
                ('maximum_stock', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='UserOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('engineer', 'Engineer'), ('manager', 'Manager'), ('admin', 'Admin')], default='operator', max_length=50)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_operators',
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('batch_weight', models.FloatField()),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('operator', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('MELTING', 'Melting'), ('TAPPING', 'Tapping'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PLANNING', max_length=50)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('actual_completion', models.DateTimeField(blank=True, null=True)),
                ('energy_used', models.FloatField(default=0.0)),
                ('production_duration', models.IntegerField(default=0)),
                ('current_stage', models.CharField(default='PLANNING', max_length=100)),
                ('alloy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alloy_api.alloy')),
            ],
            options={
                'db_table': 'production_batches',
            },
        ),
        migrations.CreateModel(
            name='FurnaceReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('temperature', models.FloatField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('power', models.FloatField()),
                ('pressure', models.FloatField()),
                ('oxygen_flow', models.FloatField()),
                ('energy_consumption', models.FloatField()),
                ('predicted_quality', models.FloatField()),
                ('predicted_completion', models.DateTimeField(blank=True, null=True)),
                ('estimated_composition', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='alloy_api.productionbatch')),
            ],
            options={
                'db_table': 'furnace_readings',
            },
        ),
        migrations.CreateModel(
            name='BatchRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('theoretical_quantity', models.FloatField()),
                ('ai_optimized_quantity', models.FloatField()),
                ('actual_added_quantity', models.FloatField(default=0.0)),
                ('addition_time', models.DateTimeField(blank=True, null=True)),
                ('recovery_percentage', models.FloatField(default=95.0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='alloy_api.productionbatch')),
            ],
            options={
                'db_table': 'batch_recipes',
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=50)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='alloy_api.productionbatch')),
            ],
            options={
                'db_table': 'anomalies',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation', models.TextField()),
                ('reason', models.TextField()),
                ('confidence', models.FloatField()),
                ('recommended_material', models.CharField(max_length=100)),
                ('recommended_quantity', models.FloatField()),
                ('expected_recovery', models.FloatField()),
                ('expected_composition', models.JSONField(default=dict)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('operator', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='alloy_api.productionbatch')),
            ],
            options={
                'db_table': 'ai_recommendations',
            },
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_composition', models.JSONField(default=dict)),
                ('target_composition', models.JSONField(default=dict)),
                ('deviation', models.JSONField(default=dict)),
                ('quality_score', models.FloatField()),
                ('energy_used', models.FloatField()),
                ('production_time', models.IntegerField()),
                ('number_of_spectrometer_samples', models.IntegerField()),
                ('number_of_ai_recommendations', models.IntegerField()),
                ('final_pass', models.BooleanField(default=True)),
                ('report_file', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='alloy_api.productionbatch')),
            ],
            options={
                'db_table': 'quality_reports',
            },
        ),
        migrations.CreateModel(
            name='SpectrometerResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('analysis_time', models.FloatField()),
                ('temperature', models.FloatField()),
                ('composition', models.JSONField(default=dict)),
                ('pass_fail', models.BooleanField(default=True)),
                ('deviation', models.JSONField(default=dict)),
                ('tolerance', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrometer_results', to='alloy_api.productionbatch')),
            ],
            options={
                'db_table': 'spectrometer_results',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alloy_api.useroperator')),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='AlloyComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element', models.CharField(db_index=True, max_length=10)),
                ('min_pct', models.FloatField()),
                ('max_pct', models.FloatField()),
                ('target_pct', models.FloatField()),
                ('alloy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='alloy_api.alloy')),
            ],
            options={
                'db_table': 'alloy_compositions',
                'unique_together': {('alloy', 'element')},
            },
        ),
    ]
