# Generated by Django 6.0.8 on 2026-08-05 20:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloy_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('health_score', models.FloatField()),
                ('estimated_remaining_life', models.CharField(max_length=100)),
                ('last_calibration', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField()),
                ('maintenance_status', models.CharField(default='Good', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipment_maintenance',
            },
        ),
    ]
