# Generated by Django 6.0.8 on 2026-08-05 21:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloy_api', '0002_equipmentmaintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('trained_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset_size', models.IntegerField()),
            ],
            options={
                'db_table': 'model_registry',
            },
        ),
        migrations.CreateModel(
            name='SmeltingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('input_parameters', models.JSONField(default=dict)),
                ('recipe_generated', models.JSONField(default=dict)),
                ('predictions', models.JSONField(default=dict)),
                ('actual_results', models.JSONField(default=dict)),
                ('selected_alloy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alloy_api.alloy')),
            ],
            options={
                'db_table': 'smelting_runs',
            },
        ),
    ]
