# Generated by Django 6.0.8 on 2026-08-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloy_api', '0003_modelregistry_smeltingrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeltingrun',
            name='ai_recommendation',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='batch_progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='current_stage',
            field=models.CharField(default='STANDBY', max_length=100),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='energy_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='estimated_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='melt_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='predicted_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='status',
            field=models.CharField(default='STANDBY', max_length=50),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='temperature',
            field=models.FloatField(default=25.0),
        ),
    ]
