# Generated by Django 6.0.8 on 2026-08-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloy_api', '0004_smeltingrun_ai_recommendation_smeltingrun_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='display_mass',
            field=models.CharField(default='0 kg', max_length=50),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='display_unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='input_unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='target_mass_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='display_mass',
            field=models.CharField(default='0 kg', max_length=50),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='display_unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='input_unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='smeltingrun',
            name='target_mass_kg',
            field=models.FloatField(default=0.0),
        ),
    ]
